### ISSUE TITLE
puppetlabs-concat dependency on version <3.0.0

### ISSUE THREAD

**Issue by yasa1987** [NTTCom-MS/eyp-netplan#3]
Hello,
I can't install youre module because I already have puppetlabs-concat in version 4.1.1. In the documentation of version 0.1.3 it written that puppetlabs-concat must correspond to following version : >= 1.2.3 < 3.0.0

Could you ensure your module works with the most recent version of provided libs ?

I got following error while trying to install
```# puppet module install eyp-netplan --environment test
Notice: Preparing to install into /etc/puppetlabs/code/environments/test/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not install module 'eyp-netplan' (???)
  No version of 'eyp-netplan' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```

**Comment by jordiprats** [comment]
Hi,
As per [PR-4](https://github.com/NTTCom-MS/eyp-netplan/pull/4), I've updated the dependencies to allow to use this module with concat > 3.0.0

best regards,
